events {}

http {
    server {
        listen 80;

        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
            proxy_set_header Host $host;
        }

        

        location / {
            proxy_pass http://go-app:8080/;
            proxy_set_header Host $host;
        }
    }
}