events {}

http {
    server {
        listen 80;

        # Prometheus
        location /prometheus/ {
            rewrite ^/prometheus(/.*)$ $1 break;
            proxy_pass http://prometheus:9090;
            proxy_set_header Host $host;
        }

        # Grafana
        location /grafana/ {
            rewrite ^/grafana(/.*)$ $1 break;
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
        }

        # Go-приложение (ВСЕГДА В КОНЦЕ!)
        location / {
            proxy_pass http://go-app:8080;
            proxy_set_header Host $host;
        }
    }
}