events {}

http {
    server {
        listen 80;

        # Prometheus
        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
        }

        # Grafana
        location /grafana/ {
            proxy_pass http://grafana:3000/;
        }

        # Go app
        location / {
            proxy_pass http://go-app:8080/;
        }
    }
}