name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Build Docker image
        run: docker build -t todo-app .

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/devops-go-app
            cd ~/devops-go-app
            git pull || git clone https://github.com/${{ github.repository }} .

            # Проверяем наличие docker-compose
            if command -v docker-compose > /dev/null 2>&1; then
              echo "Using docker-compose V1"
              docker-compose build
              docker-compose up -d
            else
              echo "Using docker compose V2"
              docker compose build
              docker compose up -d
            fi