name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий (GitHub runner сам делает checkout)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Настройка SSH для подключения к серверу
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 3. Подключаемся к серверу и деплоим через docker compose V2
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/devops-go-app
            cd ~/devops-go-app

            if [ -d ".git" ]; then
              git pull
            else
              git clone https://github.com/sonnyranger/devops-go-app .
            fi

            # Проверяем Docker Compose V2 и деплой
            if docker compose version > /dev/null 2>&1; then
              docker compose up --build --detach
              docker compose ps
            else
              echo "Error: Docker Compose V2 not found"
              exit 1
            fi